# Change these first
owner: EchterAlsFake # Your GitHub organization or username, where this repository lives
repo: status-page-server # The name of this repository

secrets:
  - NOTIFICATION_TELEGRAM
  - NOTIFICATION_TELEGRAM_BOT_KEY
  - NOTIFICATION_TELEGRAM_CHAT_ID
  - GH_PAT

sites:
  - name: Server
    url: https://echteralsfake.me/ping

status-website:
  name: Pixel Status
  introTitle: "Pixel 7 Pro Self-Hosted Services"
  theme: dark
  # Required if using the default github.io subdomain
  baseUrl: /status-page-server

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
